#!/usr/bin/env python3

import sys
from os import getenv
from datetime import date
import requests
import lxml.html

dayurl = baseurl = 'https://www.daysoftheyear.com/days'
webhook = getenv('DOTY_WEBHOOK')
day = ''
message = ''

try:
    # try file first, useful for debugging
    with open(sys.argv[1]) as file:
        html = file.read()

except:
    try:
        month = sys.argv[1]
        day = f'{int(sys.argv[2]):02d}'
    except:
        month = date.today().strftime('%b').lower()
        day = date.today().strftime('%d')

    try:
        year = sys.argv[3]
        dayurl = f'{baseurl}/{month}/{day}/{year}'
    except:
        dayurl = f'{baseurl}/{month}/{day}'

    r = requests.get(dayurl)
    html = r.content

page = lxml.html.document_fromstring(html)

for section in page.cssselect('.section.section--group'):
    # this gives 2 sections: one for the day, one for the month
    head = ' '.join(section.cssselect('.heading')[0].text.split())
    if not head:
        head = page.cssselect('.banner__title.heading')[0].text + ' is ...'
    message += f'{head}'
    links = []
    for event in section.cssselect('.js-link-target'):
        name = event.text_content().replace('\xa0', ' ')
        url = event.get('href')
        links.append(f'[{name}]({url})')
    if links:
        message += f' {", ".join(links)}.\n'
    else:
        message += ' nothing special.\n'
    # print month-section only on the first day of the month
    if day != '01': break

if webhook:
    if webhook.find('webhook.office.com/') >= 0:
        payload = {
            '@context': 'https://schema.org/extensions',
            '@type': 'MessageCard',
            'text': message
        }
    else:
        payload = {'username': 'Doty', 'text': message }
    r = requests.post(webhook, json=payload)
    if not r.ok:
        print(f'{r.status_code} {r.reason}', file=sys.stderr)
        sys.exit(1)
else:
    print(dayurl)
    print(message, end='')
