#!/usr/bin/env python3

import sys
from os import getenv
from datetime import date
import requests
import lxml.html

baseurl = 'https://www.daysoftheyear.com/days'
webhook = getenv('DOTY_WEBHOOK')
day = ''
message = ''

try:
    # try file first, useful for debugging
    with open(sys.argv[1]) as file:
        html = file.read()

except:
    try:
        month = sys.argv[1]
        day = '{:02d}'.format(int(sys.argv[2]))
        day = f'{int(sys.argv[2]):02d}'
    except:
        month = date.today().strftime('%b').lower()
        day = date.today().strftime('%d')

    try:
        year = sys.argv[3]
        url = f'{baseurl}/{month}/{day}/{year}'
    except:
        url = f'{baseurl}/{month}/{day}'

    r = requests.get(url)
    html = r.content

page = lxml.html.document_fromstring(html)

for section in page.cssselect('.section.section--group'):
    # this gives 2 sections: one for the day, one for the month
    head = section.cssselect('.heading')[0].text
    message += f'{head}'
    links = []
    for event in section.cssselect('.js-link-target'):
        name = event.text
        url = event.get('href')
        links.append(f'[{name}]({url})')
    if links:
        message += f' {", ".join(links)}. '
    else:
        message += ' nothing special. '
    # print month-section only on the first day of the month
    if day != '01': break

if webhook:
    payload = {'username': 'Doty', 'text': message }
    r = requests.post(webhook, json=payload)
    if r.ok:
        sys.exit(0)
    else:
        print(f'{r.status_code} {r.reason}', file=sys.stderr)
        sys.exit(1)
else:
    print(message)
